version: '3'
services:
  notebook:
    container_name: jupyter_notebook
    labels:
      description: Jupyter Notebook
      name: jupyter 
    ports:
      - "8888:8888"
    volumes:
      - ~/Documents/notebooks:/home/notebooks
    build: . 
