version: '3'
services:
  notebook:
    container_name: openstudio-jupyter
    labels:
      description: Jupyter DataScience Notebook
      name: openstudio-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ~/Documents/notebooks:/home/notebooks
    build: . 
